M48
; DRILL file {KiCad (6.0.4)} date Mon Oct 24 21:41:42 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-24T21:41:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X3.4818Y-1.8624
X3.4818Y-3.3876
T2
X8.9548Y-1.74
X8.9548Y-5.24
T3
X4.29Y-1.8241
T0
M30
